// ============================================================================
// Typed ID Newtypes
//
// Opaque wrappers around String IDs that prevent accidental mixing of a
// ThreadId with a RunId at the type level — compile-time safety at zero
// runtime cost.
//
// All IDs are UUID v4 strings generated by `::new()`. External IDs arriving
// from the gateway or agent are wrapped with `From<String>` / `From<&str>`.
// ============================================================================

macro_rules! typed_id {
    ($name:ident) => {
        #[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
        pub struct $name(pub String);

        impl $name {
            /// Generate a fresh random UUID-backed ID.
            pub fn new() -> Self {
                Self(uuid::Uuid::new_v4().to_string())
            }

            /// Borrow as a `&str` without allocating.
            pub fn as_str(&self) -> &str {
                &self.0
            }
        }

        impl Default for $name {
            fn default() -> Self {
                Self::new()
            }
        }

        impl std::fmt::Display for $name {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                f.write_str(&self.0)
            }
        }

        impl From<String> for $name {
            fn from(s: String) -> Self {
                Self(s)
            }
        }

        impl From<&str> for $name {
            fn from(s: &str) -> Self {
                Self(s.to_string())
            }
        }
    };
}

// ThreadId — identifies a persistent conversation, owned by the session service.
typed_id!(ThreadId);

// RunId — identifies a single agent execution cycle within a Thread.
typed_id!(RunId);

// MessageId — identifies a persisted message (user or assistant) within a Thread.
typed_id!(MessageId);
